project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "An R Package for Dungeons & Dragons: `dndR`"
  favicon: images/dndR_hex.png
  repo-url: https://github.com/njlyon0/dndR
  repo-actions: [issue]
  twitter-card: true
  navbar:
    background: primary
    right:
      - authors.qmd
      - icon: github
        href: https://github.com/njlyon0/dndR
  sidebar:
    style: "docked"
    background: secondary
    search: true
    contents: 
      - href: index.qmd
        text: "Package Overview"
      - section: "For Everyone"
        contents: 
          - href: dice.qmd
          - href: create-characters.qmd
      - section: "For DMs"
        contents: 
          - href: encounter-balance.qmd
          - href: create-monsters.qmd
          - href: party_diagram.qmd
  page-footer:
    center: "Copyright 2022, Nicholas J Lyon"
    background: primary
  margin-footer: <img src="images/dndR_hex.png" width = "40%" />

format:
  html:
    theme:
      light: lyonlight.scss
      dark: lyondark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
