---
title: "Non-Player Characters"
---

> **DM:** "You walk into the tavern and glance around the poorly lit room. In a corner booth, you catch sight of the betrayer you've been hunting these past two weeks--Tymoth Grissel. You nearly had him in the Sootpile mountains but that rockslide allowed him to escape by the skin of his teeth. He won't escape this time."

> **Player:** "Cool, cool...but who *else* is in the tavern?

> **DM:** ...

When I'm DMing, I sometimes struggle with improvising background NPCs (non-player characters) that aren't relevant to the current questlines when my player ask about them. To hopefully help fellow DMs, `dndR` includes a function to let you quickly respond in situations like the one I've described above.

`npc_creator` quickly selects a random race and job for however many NPCs you need. The function returns this as a dataframe in case you had some follow-up processing you wished to do but I find myself running the function without assigning it to an object so that it prints in the console.

```{r npc-creator-fxn}
dndR::npc_creator(npc_count = 3)
```

If your players decide to go chat with the goblin carpenter passing them on the street (or whoever else they cross paths with) you can then improv more details about the NPC as needed. Hopefully this function helps you skip the "uh..." step of trying to on-the-fly come up with some brief NPC descriptions.

Note that because both NPC race and job are selected randomly you may wind up with some unusual combinations. I hope that adds to the fun but feel free to re-run `npc_creator` until you get NPCs that fit your world and intended tone.
